controller:
  agentListenerEnabled: true
  agentListenerPort: 50000

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - credentials-binding

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

persistence:
  enabled: true
  size: 8Gi

agent:
  enabled: true